language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

before_script: composer install --dev

matrix:
  allow_failures:
    - env: DOCTRINE_VERSION=dev-master
    - php: hhvm
    - php: 5.6
      DOCTRINE_VERSION=2.8.*
      DOCTRINE_VERSION=2.9.*
      DOCTRINE_VERSION=2.10.*
      DOCTRINE_VERSION=2.11.*
      DOCTRINE_VERSION=2.12.*

env:
  - DOCTRINE_VERSION=2.1.*
  - DOCTRINE_VERSION=2.2.*
  - DOCTRINE_VERSION=2.3.*
  - DOCTRINE_VERSION=2.4.*
  - DOCTRINE_VERSION=2.5.*
  - DOCTRINE_VERSION=2.6.*
  - DOCTRINE_VERSION=2.7.*
  - DOCTRINE_VERSION=2.8.*
  - DOCTRINE_VERSION=2.9.*
  - DOCTRINE_VERSION=2.10.*
  - DOCTRINE_VERSION=2.11.*
  - DOCTRINE_VERSION=2.12.*
  - DOCTRINE_VERSION=dev-master

notifications:
  email: alayn@barnetik.com

before_script:
  - composer require --no-update doctrine/common $DOCTRINE_VERSION
  - composer update

cache:
  directories:
    - $COMPOSER_CACHE_DIR
